# Travis CI configuration
os: osx
osx_image: xcode11.3
language: swift

branch:
  only:
    - master
    - /(\d+\.)?(\d+\.)?(\*|\d+)$/

env:
  global:
    - XCODEPROJ=LeagueAPI/LeagueAPI.xcodeproj
    - FRAMEWORK_IOS_SCHEME=LeagueAPI-iOS
    - FRAMEWORK_TVOS_SCHEME=LeagueAPI-TvOS
    - FRAMEWORK_WATCHOS_SCHEME=LeagueAPI-WatchOS
    - FRAMEWORK_MACOS_SCHEME=LeagueAPI-MacOS

jobs:
  include:
    - stage: "Compile iOS"
      name: "iOS 13"
      env: DESTINATION="OS=13.3,name=iPhone 11 Pro" SCHEME="$FRAMEWORK_IOS_SCHEME"
      script: ./scripts/compile.sh

    - stage: "Compile iOS"
      name: "iOS 12"
      env: DESTINATION="OS=12.4,name=iPhone XS" SCHEME="$FRAMEWORK_IOS_SCHEME"
      script: ./scripts/compile.sh
      if: tag IS present

    - stage: "Compile iOS"
      name: "iOS 11"
      env: DESTINATION="OS=11.4,name=iPhone X" SCHEME="$FRAMEWORK_IOS_SCHEME"
      script: ./scripts/compile.sh
      if: tag IS present

    - stage: "Compile iOS"
      name: "iOS 10"
      env: DESTINATION="OS=10.3.1,name=iPhone 7" SCHEME="$FRAMEWORK_IOS_SCHEME"
      script: ./scripts/compile.sh
      if: tag IS present

    - stage: "Compile iOS"
      name: "iOS 9"
      env: DESTINATION="OS=9.3,name=iPhone 6s" SCHEME="$FRAMEWORK_IOS_SCHEME"
      script: ./scripts/compile.sh
      if: tag IS present

    - stage: "Compile iOS"
      name: "iOS 8"
      env: DESTINATION="OS=8.1,name=iPhone 6" SCHEME="$FRAMEWORK_IOS_SCHEME"
      script: ./scripts/compile.sh
      if: tag IS present

    - stage: "Compile TvOS"
      name: "TvOS 13"
      env: DESTINATION="OS=13.2,name=Apple TV 4K" SCHEME="$FRAMEWORK_TVOS_SCHEME"
      script: ./scripts/compile.sh

    - stage: "Compile TvOS"
      name: "TvOS 12"
      env: DESTINATION="OS=12.4,name=Apple TV 4K" SCHEME="$FRAMEWORK_TVOS_SCHEME"
      script: ./scripts/compile.sh
      if: tag IS present

    - stage: "Compile TvOS"
      name: "TvOS 11"
      env: DESTINATION="OS=11.4,name=Apple TV 4K" SCHEME="$FRAMEWORK_TVOS_SCHEME"
      script: ./scripts/compile.sh
      if: tag IS present

    - stage: "Compile TvOS"
      name: "TvOS 10"
      env: DESTINATION="OS=10.2,name=Apple TV 1080p" SCHEME="$FRAMEWORK_TVOS_SCHEME"
      script: ./scripts/compile.sh
      if: tag IS present

    - stage: "Compile TvOS"
      name: "TvOS 9"
      env: DESTINATION="OS=9.0,name=Apple TV 1080p" SCHEME="$FRAMEWORK_TVOS_SCHEME"
      script: ./scripts/compile.sh
      if: tag IS present

    - stage: "Compile WatchOS"
      name: "WatchOS 6"
      env: DESTINATION="OS=6.1,name=Apple Watch Series 5 - 44mm" SCHEME="$FRAMEWORK_WATCHOS_SCHEME"
      script: ./scripts/compile.sh

    - stage: "Compile WatchOS"
      name: "WatchOS 5"
      env: DESTINATION="OS=5.3,name=Apple Watch Series 4 - 44mm" SCHEME="$FRAMEWORK_WATCHOS_SCHEME"
      script: ./scripts/compile.sh
      if: tag IS present

    - stage: "Compile WatchOS"
      name: "WatchOS 4"
      env: DESTINATION="OS=4.2,Apple Watch Series 3 - 42mm" SCHEME="$FRAMEWORK_WATCHOS_SCHEME"
      script: ./scripts/compile.sh
      if: tag IS present

    - stage: "Compile WatchOS"
      name: "WatchOS 3"
      env: DESTINATION="OS=3.2,name=Apple Watch Series 2 - 42mm" SCHEME="$FRAMEWORK_WATCHOS_SCHEME"
      script: ./scripts/compile.sh
      if: tag IS present

    - stage: "Compile WatchOS"
      name: "WatchOS 2"
      env: DESTINATION="OS=2.0,name=Apple Watch" SCHEME="$FRAMEWORK_WATCHOS_SCHEME"
      script: ./scripts/compile.sh
      if: tag IS present

    - stage: "Compile MacOS"
      name: "MacOS x86_64"
      env: DESTINATION="arch=x86_64" SCHEME="$FRAMEWORK_MACOS_SCHEME"
      script: ./scripts/compile.sh

    - stage: Deploy
      name: "Release $TRAVIS_TAG"
      script: ./scripts/deploy_process.sh

stages:
  - name: "Compile iOS"
  - name: "Compile TvOS"
  - name: "Compile WatchOS"
  - name: "Compile MacOS"
  - name: Deploy
    if: tag IS present
